"""packet 9 reflection engine and daily founder report

Revision ID: 2672f4c748a7
Revises: 274f46334d7a
Create Date: 2026-08-30 12:57:22.494139

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '2672f4c748a7'
down_revision: str | None = '274f46334d7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('simulation_day', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', name='reflection_status'), nullable=False),
    sa.Column('open_question', sa.Text(), nullable=True),
    sa.Column('suggested_follow_up', sa.Text(), nullable=True),
    sa.Column('supersedes_reflection_id', sa.Integer(), nullable=True),
    sa.Column('source_memory_ids', sa.JSON(), nullable=False),
    sa.Column('source_research_ids', sa.JSON(), nullable=False),
    sa.Column('source_belief_ids', sa.JSON(), nullable=False),
    sa.Column('source_conversation_ids', sa.JSON(), nullable=False),
    sa.Column('source_rabbit_hole_ids', sa.JSON(), nullable=False),
    sa.Column('source_wall_post_ids', sa.JSON(), nullable=False),
    sa.Column('source_reflection_ids', sa.JSON(), nullable=False),
    sa.Column('last_accessed_sim_day', sa.Integer(), nullable=True),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_reflections_agent_id_agents')),
    sa.ForeignKeyConstraint(['supersedes_reflection_id'], ['agent_reflections.id'], name=op.f('fk_agent_reflections_supersedes_reflection_id_agent_reflections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_reflections'))
    )
    with op.batch_alter_table('agent_reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_reflections_agent_id'), ['agent_id'], unique=False)

    # server_default on every NOT NULL column below (Packet 7's precedent):
    # agents already holds the Founding Eight, so a live database needs a
    # backfill value, not just an ORM-side default for new rows.
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflection_pressure', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('last_reflection_sim_day', sa.Integer(), nullable=True))

    # daily_reports has never been populated by any code before this packet
    # (confirmed by inspection), so these server_defaults exist purely for
    # the same "any existing database" discipline, not because real rows
    # need backfilling.
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('structured', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('had_meaningful_activity', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('is_fixture', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_unique_constraint('uq_daily_reports_day_number', ['day_number'])
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sqlite.JSON(), nullable=False, server_default='{}'))
        batch_op.drop_constraint('uq_daily_reports_day_number', type_='unique')
        batch_op.drop_column('is_fixture')
        batch_op.drop_column('had_meaningful_activity')
        batch_op.drop_column('structured')
        batch_op.drop_column('summary_text')
        batch_op.drop_column('title')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('last_reflection_sim_day')
        batch_op.drop_column('reflection_pressure')

    with op.batch_alter_table('agent_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_reflections_agent_id'))

    op.drop_table('agent_reflections')
    # ### end Alembic commands ###
