"""packet 5: research provenance, claims, evidence links

Revision ID: 4bac3defad23
Revises: e84816e741ee
Create Date: 2026-08-29 23:12:34.466100

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4bac3defad23'
down_revision: str | None = 'e84816e741ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('REAL_WORLD_FACT', 'SOURCE_CLAIM', 'RESEARCH_FINDING', 'AGENT_INFERENCE', 'AGENT_BELIEF', 'HYPOTHESIS', 'SPECULATION', 'SIMULATION_EVENT', 'CREATIVE_CONTENT', name='finding_classification'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['research_findings.id'], name=op.f('fk_claims_finding_id_research_findings')),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_claims_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_research_session_id'), ['research_session_id'], unique=False)

    op.create_table('research_source_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('research_query_id', sa.Integer(), nullable=True),
    sa.Column('locator', sa.String(length=255), nullable=True),
    sa.Column('excerpt_text', sa.Text(), nullable=False),
    sa.Column('excerpt_sha256', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['research_query_id'], ['research_queries.id'], name=op.f('fk_research_source_passages_research_query_id_research_queries')),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_source_passages_source_id_research_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_source_passages'))
    )
    with op.batch_alter_table('research_source_passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_source_passages_research_query_id'), ['research_query_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_source_passages_source_id'), ['source_id'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Enum('SUPPORTS', 'CONTRADICTS', 'CONTEXT', name='evidence_relation'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_evidence_claim_id_claims')),
    sa.ForeignKeyConstraint(['passage_id'], ['research_source_passages.id'], name=op.f('fk_claim_evidence_passage_id_research_source_passages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence'))
    )
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_passage_id'), ['passage_id'], unique=False)

    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        # server_default so this also applies to a database that already has
        # research_sessions rows; new rows take the ORM default.
        batch_op.add_column(
            sa.Column('is_fixture', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('provider_result_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_research_sources_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_provider'))
        batch_op.drop_column('domain')
        batch_op.drop_column('provider_result_id')
        batch_op.drop_column('provider')

    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_fixture')

    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_passage_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_claim_id'))

    op.drop_table('claim_evidence')
    with op.batch_alter_table('research_source_passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_source_passages_source_id'))
        batch_op.drop_index(batch_op.f('ix_research_source_passages_research_query_id'))

    op.drop_table('research_source_passages')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_research_session_id'))
        batch_op.drop_index(batch_op.f('ix_claims_finding_id'))

    op.drop_table('claims')
    # ### end Alembic commands ###
