"""packet 3: llm_runs and event causation

Revision ID: 5cac9c1fd671
Revises: cafb5746c93e
Create Date: 2026-08-29 02:02:06.252566

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5cac9c1fd671'
down_revision: str | None = 'cafb5746c93e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_llm_runs_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_runs'))
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_purpose'), ['purpose'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sim_period', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('causation_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_sim_day'), ['sim_day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_sim_day'))
        batch_op.drop_index(batch_op.f('ix_events_correlation_id'))
        batch_op.drop_column('causation_id')
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('sim_period')
        batch_op.drop_column('sim_day')

    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_runs_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_agent_id'))

    op.drop_table('llm_runs')
    # ### end Alembic commands ###
