"""packet 10 live research providers

Revision ID: 7edb9c8a3cb6
Revises: 2672f4c748a7
Create Date: 2026-08-30 18:28:32.309823

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7edb9c8a3cb6'
down_revision: str | None = '2672f4c748a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_provider_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('queries_executed', sa.Integer(), nullable=False),
    sa.Column('results_returned', sa.Integer(), nullable=False),
    sa.Column('sources_fetched', sa.Integer(), nullable=False),
    sa.Column('fetch_failures', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('provider_reported_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_research_provider_usage_agent_id_agents')),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_research_provider_usage_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_provider_usage'))
    )
    with op.batch_alter_table('research_provider_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_provider_usage_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_provider_usage_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_provider_usage_research_session_id'), ['research_session_id'], unique=True)

    # server_default (Packet 7's precedent): research_sources may already
    # hold rows from earlier packets' research sessions, and every prior
    # source is honestly UNKNOWN — nothing about it was actually classified.
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'quality_tier',
                sa.Enum('PRIMARY', 'OFFICIAL', 'NEWS', 'ACADEMIC', 'INDUSTRY', 'BLOG', 'COMMUNITY', 'UNKNOWN', name='source_quality_tier'),
                nullable=False,
                server_default='UNKNOWN',
            )
        )
        batch_op.add_column(sa.Column('provider_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_column('provider_rank')
        batch_op.drop_column('quality_tier')

    with op.batch_alter_table('research_provider_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_provider_usage_research_session_id'))
        batch_op.drop_index(batch_op.f('ix_research_provider_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_research_provider_usage_agent_id'))

    op.drop_table('research_provider_usage')
    # ### end Alembic commands ###
