"""provider rate limit circuit breaker pause reason

Revision ID: a11c5ab569f8
Revises: fc9e4f3df6fe
Create Date: 2026-09-22 23:46:43.850115

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a11c5ab569f8'
down_revision: str | None = 'fc9e4f3df6fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_clock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_reason', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_clock', schema=None) as batch_op:
        batch_op.drop_column('pause_reason')
    # ### end Alembic commands ###
