"""packet 11 live llm intelligence

Revision ID: bbcc2d11aceb
Revises: 7edb9c8a3cb6
Create Date: 2026-08-30 23:47:12.541104

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bbcc2d11aceb'
down_revision: str | None = '7edb9c8a3cb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default (established precedent since Packet 7): llm_runs already
    # holds rows from every prior packet, and none of them were retried in
    # the sense this column now tracks, so 0 is the honest backfill value.
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
