"""initial phase 1 schema

Revision ID: cafb5746c93e
Revises: 
Create Date: 2026-08-29 01:20:52.709348

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cafb5746c93e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('voice', sa.Text(), nullable=False),
    sa.Column('current_location', sa.String(length=64), nullable=True),
    sa.Column('current_activity', sa.Text(), nullable=True),
    sa.Column('interaction_target', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_id'), ['agent_id'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('RESEARCH_SHARING', 'WALL_ACTIVITY', 'DISAGREEMENT', 'SIMILAR_DISCOVERY', 'MORNING_GATHERING', 'RANDOM_SOCIAL', 'FOUNDER_MESSAGE', name='conversation_trigger'), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='conversation_status'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reports'))
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_day_number'), ['day_number'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=True)

    op.create_table('simulation_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('current_period', sa.String(length=32), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('last_advanced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_clock'))
    )
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_state'))
    )
    with op.batch_alter_table('world_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_state_key'), ['key'], unique=True)

    op.create_table('agent_beliefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONAL', 'SUPPORTED', 'CONTESTED', 'REJECTED', 'RETIRED', name='belief_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_beliefs_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_beliefs'))
    )
    with op.batch_alter_table('agent_beliefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_beliefs_agent_id'), ['agent_id'], unique=False)

    op.create_table('agent_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('interest', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('last_engaged', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_interests_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_interests'))
    )
    with op.batch_alter_table('agent_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_interests_agent_id'), ['agent_id'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_conversation_messages_agent_id_agents')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('AGENT_WOKE', 'AGENT_RESEARCH_STARTED', 'SEARCH_EXECUTED', 'SOURCE_DISCOVERED', 'RESEARCH_COMPLETED', 'FINDING_CREATED', 'FINDING_SHARED', 'RESEARCH_WALL_POSTED', 'RABBIT_HOLE_CREATED', 'RABBIT_HOLE_JOINED', 'RABBIT_HOLE_UPDATED', 'CONVERSATION_STARTED', 'CONVERSATION_MESSAGE', 'CONVERSATION_ENDED', 'CLAIM_CHALLENGED', 'FOLLOWUP_QUESTION_CREATED', 'BELIEF_CREATED', 'BELIEF_UPDATED', 'BELIEF_REJECTED', 'INTEREST_INCREASED', 'INTEREST_DECREASED', 'MEMORY_CREATED', 'FOUNDER_MESSAGE', 'DAILY_REPORT_CREATED', name='event_type'), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_events_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)

    op.create_table('founder_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_agent_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.agent_id'], name=op.f('fk_founder_messages_target_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_founder_messages'))
    )
    with op.batch_alter_table('founder_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_messages_target_agent_id'), ['target_agent_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.Enum('EPISODIC', 'SEMANTIC', 'SOCIAL', 'INTEREST', name='memory_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_ids', sa.JSON(), nullable=False),
    sa.Column('last_recalled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_memories_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_agent_id'), ['agent_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_agent_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_agent_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['agents.agent_id'], name=op.f('fk_messages_recipient_agent_id_agents')),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.agent_id'], name=op.f('fk_messages_sender_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_recipient_agent_id'), ['recipient_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_agent_id'), ['sender_agent_id'], unique=False)

    op.create_table('rabbit_holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('originating_agent_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_strength', sa.Enum('WEAK', 'DEVELOPING', 'MODERATE', 'STRONG', 'CONFLICTING', 'INSUFFICIENT', name='evidence_strength'), nullable=False),
    sa.Column('current_hypothesis', sa.Text(), nullable=True),
    sa.Column('counterarguments', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('activity_level', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'HOT', 'COOLING', 'DORMANT', 'RESOLVED', 'ABANDONED', name='rabbit_hole_status'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['originating_agent_id'], ['agents.agent_id'], name=op.f('fk_rabbit_holes_originating_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rabbit_holes'))
    )
    with op.batch_alter_table('rabbit_holes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rabbit_holes_originating_agent_id'), ['originating_agent_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_a_id', sa.String(length=64), nullable=False),
    sa.Column('agent_b_id', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_a_id'], ['agents.agent_id'], name=op.f('fk_relationships_agent_a_id_agents')),
    sa.ForeignKeyConstraint(['agent_b_id'], ['agents.agent_id'], name=op.f('fk_relationships_agent_b_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_agent_a_id'), ['agent_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_agent_b_id'), ['agent_b_id'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', 'ABANDONED', name='research_status'), nullable=False),
    sa.Column('evidence_strength', sa.Enum('WEAK', 'DEVELOPING', 'MODERATE', 'STRONG', 'CONFLICTING', 'INSUFFICIENT', name='evidence_strength'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('related_research', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_research_sessions_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_research_id'), ['research_id'], unique=True)

    op.create_table('rabbit_hole_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_hole_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_rabbit_hole_members_agent_id_agents')),
    sa.ForeignKeyConstraint(['rabbit_hole_id'], ['rabbit_holes.id'], name=op.f('fk_rabbit_hole_members_rabbit_hole_id_rabbit_holes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rabbit_hole_members'))
    )
    with op.batch_alter_table('rabbit_hole_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rabbit_hole_members_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rabbit_hole_members_rabbit_hole_id'), ['rabbit_hole_id'], unique=False)

    op.create_table('rabbit_hole_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_hole_id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['rabbit_hole_id'], ['rabbit_holes.id'], name=op.f('fk_rabbit_hole_research_rabbit_hole_id_rabbit_holes')),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_rabbit_hole_research_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rabbit_hole_research'))
    )
    with op.batch_alter_table('rabbit_hole_research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rabbit_hole_research_rabbit_hole_id'), ['rabbit_hole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rabbit_hole_research_research_session_id'), ['research_session_id'], unique=False)

    op.create_table('research_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('REAL_WORLD_FACT', 'SOURCE_CLAIM', 'RESEARCH_FINDING', 'AGENT_INFERENCE', 'AGENT_BELIEF', 'HYPOTHESIS', 'SPECULATION', 'SIMULATION_EVENT', 'CREATIVE_CONTENT', name='finding_classification'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_research_findings_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_findings'))
    )
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_findings_research_session_id'), ['research_session_id'], unique=False)

    op.create_table('research_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_research_queries_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_queries'))
    )
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_queries_research_session_id'), ['research_session_id'], unique=False)

    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_session_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_research_sources_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources'))
    )
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sources_research_session_id'), ['research_session_id'], unique=False)

    op.create_table('research_wall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('post_type', sa.Enum('FINDING', 'SOURCE', 'QUESTION', 'HYPOTHESIS', 'DISAGREEMENT', 'CONNECTION', 'MYSTERY', 'RABBIT_HOLE_SUGGESTION', name='wall_post_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_research_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_research_wall_agent_id_agents')),
    sa.ForeignKeyConstraint(['related_research_id'], ['research_sessions.research_id'], name=op.f('fk_research_wall_related_research_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_wall'))
    )
    with op.batch_alter_table('research_wall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_wall_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_wall_related_research_id'), ['related_research_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_wall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_wall_related_research_id'))
        batch_op.drop_index(batch_op.f('ix_research_wall_agent_id'))

    op.drop_table('research_wall')
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_research_session_id'))

    op.drop_table('research_sources')
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_queries_research_session_id'))

    op.drop_table('research_queries')
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_findings_research_session_id'))

    op.drop_table('research_findings')
    with op.batch_alter_table('rabbit_hole_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rabbit_hole_research_research_session_id'))
        batch_op.drop_index(batch_op.f('ix_rabbit_hole_research_rabbit_hole_id'))

    op.drop_table('rabbit_hole_research')
    with op.batch_alter_table('rabbit_hole_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rabbit_hole_members_rabbit_hole_id'))
        batch_op.drop_index(batch_op.f('ix_rabbit_hole_members_agent_id'))

    op.drop_table('rabbit_hole_members')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sessions_research_id'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_agent_id'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_agent_b_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_agent_a_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('rabbit_holes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rabbit_holes_originating_agent_id'))

    op.drop_table('rabbit_holes')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_agent_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_agent_id'))

    op.drop_table('messages')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_agent_id'))

    op.drop_table('memories')
    with op.batch_alter_table('founder_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_messages_target_agent_id'))

    op.drop_table('founder_messages')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_agent_id'))

    op.drop_table('events')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_agent_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('agent_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_interests_agent_id'))

    op.drop_table('agent_interests')
    with op.batch_alter_table('agent_beliefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_beliefs_agent_id'))

    op.drop_table('agent_beliefs')
    with op.batch_alter_table('world_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_state_key'))

    op.drop_table('world_state')
    op.drop_table('simulation_clock')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_name'))

    op.drop_table('locations')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_day_number'))

    op.drop_table('daily_reports')
    op.drop_table('conversations')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_agent_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
