"""packet 4 exposures and conversation state

Revision ID: e84816e741ee
Revises: 5cac9c1fd671
Create Date: 2026-08-29 22:38:31.867441

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e84816e741ee'
down_revision: str | None = '5cac9c1fd671'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('exposure_type', sa.Enum('CREATED', 'DIRECT_MESSAGE', 'CONVERSATION', 'SHARED_FINDING', 'WALL_GLIMPSE', 'WALL_READ', 'SOURCE_READ', 'FOUNDER_MESSAGE', name='exposure_type'), nullable=False),
    sa.Column('exposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_exposures_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_exposures'))
    )
    with op.batch_alter_table('agent_exposures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_exposures_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_exposures_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_exposures_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        # server_default so this also applies to a database that already holds
        # conversation rows; new rows take the ORM default.
        batch_op.add_column(
            sa.Column('consecutive_silences', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('departed_agent_ids', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('ACTIVE', 'WINDING_DOWN', 'ENDED', name='conversation_status'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_conversations_correlation_id'), ['correlation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_correlation_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'WINDING_DOWN', 'ENDED', name='conversation_status'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('departed_agent_ids')
        batch_op.drop_column('consecutive_silences')

    with op.batch_alter_table('agent_exposures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_exposures_entity_type'))
        batch_op.drop_index(batch_op.f('ix_agent_exposures_entity_id'))
        batch_op.drop_index(batch_op.f('ix_agent_exposures_agent_id'))

    op.drop_table('agent_exposures')
    # ### end Alembic commands ###
