"""packet 6: research wall connections, rabbit hole heat, belief basis

Revision ID: ea12ac3f2572
Revises: 4bac3defad23
Create Date: 2026-08-30 00:16:51.363355

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ea12ac3f2572'
down_revision: str | None = '4bac3defad23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belief_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belief_id', sa.Integer(), nullable=False),
    sa.Column('basis_type', sa.String(length=32), nullable=False),
    sa.Column('basis_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.Enum('STRENGTHENS', 'WEAKENS', 'REJECTS', name='belief_basis_relation'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['agent_beliefs.id'], name=op.f('fk_belief_basis_belief_id_agent_beliefs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_belief_basis'))
    )
    with op.batch_alter_table('belief_basis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_belief_basis_belief_id'), ['belief_id'], unique=False)

    with op.batch_alter_table('rabbit_hole_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('rabbit_holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_day', sa.Integer(), nullable=True))

    with op.batch_alter_table('research_wall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_wall_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_rabbit_hole_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_research_wall_related_rabbit_hole_id'), ['related_rabbit_hole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_wall_related_wall_post_id'), ['related_wall_post_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_research_wall_related_rabbit_hole_id_rabbit_holes'), 'rabbit_holes', ['related_rabbit_hole_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_research_wall_related_wall_post_id_research_wall'), 'research_wall', ['related_wall_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_wall', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_research_wall_related_wall_post_id_research_wall'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_research_wall_related_rabbit_hole_id_rabbit_holes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_research_wall_related_wall_post_id'))
        batch_op.drop_index(batch_op.f('ix_research_wall_related_rabbit_hole_id'))
        batch_op.drop_column('related_rabbit_hole_id')
        batch_op.drop_column('related_wall_post_id')

    with op.batch_alter_table('rabbit_holes', schema=None) as batch_op:
        batch_op.drop_column('last_activity_day')

    with op.batch_alter_table('rabbit_hole_members', schema=None) as batch_op:
        batch_op.drop_column('left_at')

    with op.batch_alter_table('belief_basis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_belief_basis_belief_id'))

    op.drop_table('belief_basis')
    # ### end Alembic commands ###
