"""agent question persistent unresolved curiosity

Revision ID: fc9e4f3df6fe
Revises: bbcc2d11aceb
Create Date: 2026-09-02 16:33:34.577805

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc9e4f3df6fe'
down_revision: str | None = 'bbcc2d11aceb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESEARCHING', 'RESOLVED', 'DORMANT', 'ABANDONED', name='agent_question_status'), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('last_engaged_sim_day', sa.Integer(), nullable=True),
    sa.Column('origin_memory_id', sa.Integer(), nullable=True),
    sa.Column('origin_reflection_id', sa.Integer(), nullable=True),
    sa.Column('origin_conversation_id', sa.Integer(), nullable=True),
    sa.Column('origin_research_session_id', sa.String(length=64), nullable=True),
    sa.Column('research_session_id', sa.String(length=64), nullable=True),
    sa.Column('rabbit_hole_id', sa.Integer(), nullable=True),
    sa.Column('reformulated_from_id', sa.Integer(), nullable=True),
    sa.Column('reformulated_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_questions_agent_id_agents')),
    sa.ForeignKeyConstraint(['origin_conversation_id'], ['conversations.id'], name=op.f('fk_agent_questions_origin_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['origin_memory_id'], ['memories.id'], name=op.f('fk_agent_questions_origin_memory_id_memories')),
    sa.ForeignKeyConstraint(['origin_reflection_id'], ['agent_reflections.id'], name=op.f('fk_agent_questions_origin_reflection_id_agent_reflections')),
    sa.ForeignKeyConstraint(['origin_research_session_id'], ['research_sessions.research_id'], name=op.f('fk_agent_questions_origin_research_session_id_research_sessions')),
    sa.ForeignKeyConstraint(['rabbit_hole_id'], ['rabbit_holes.id'], name=op.f('fk_agent_questions_rabbit_hole_id_rabbit_holes')),
    sa.ForeignKeyConstraint(['reformulated_from_id'], ['agent_questions.id'], name=op.f('fk_agent_questions_reformulated_from_id_agent_questions')),
    sa.ForeignKeyConstraint(['reformulated_into_id'], ['agent_questions.id'], name=op.f('fk_agent_questions_reformulated_into_id_agent_questions')),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.research_id'], name=op.f('fk_agent_questions_research_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_questions'))
    )
    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_questions_agent_id'), ['agent_id'], unique=False)

    # Note: autogenerate also proposes an events.event_type column type
    # rewrite here (VARCHAR -> a wider Enum literal) every time EventType
    # gains new members, same as every prior packet's migration — SQLite
    # never enforces that enum's members as a real constraint, so it is
    # deliberately omitted, matching Packet 7-11's own migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_questions_agent_id'))

    op.drop_table('agent_questions')
    # ### end Alembic commands ###
